// <auto-generated />
using System;
using Backlog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backlog.Api.Migrations;
[DbContext(typeof(BacklogDbContext))]
[Migration("20211024103019_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.10")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("Backlog.Core.Bug", b =>
            {
                b.Property<Guid>("BugId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("BugId");

                b.ToTable("Bugs");
            });

        modelBuilder.Entity("Backlog.Core.CompetencyLevel", b =>
            {
                b.Property<Guid>("CompetencyLevelId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CompetencyLevelId");

                b.ToTable("CompetencyLevels");
            });

        modelBuilder.Entity("Backlog.Core.Profile", b =>
            {
                b.Property<Guid>("ProfileId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Firstname")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Lastname")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ProfileId");

                b.ToTable("Profiles");
            });

        modelBuilder.Entity("Backlog.Core.Status", b =>
            {
                b.Property<Guid>("StatusId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("StatusId");

                b.ToTable("Statuses");
            });

        modelBuilder.Entity("Backlog.Core.StoredEvent", b =>
            {
                b.Property<Guid>("StoredEventId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Aggregate")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AggregateDotNetType")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("CorrelationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Data")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DotNetType")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Sequence")
                    .HasColumnType("int");

                b.Property<Guid>("StreamId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Type")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Version")
                    .HasColumnType("int");

                b.HasKey("StoredEventId");

                b.ToTable("StoredEvents");
            });

        modelBuilder.Entity("Backlog.Core.Story", b =>
            {
                b.Property<Guid>("StoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AcceptanceCriteria")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("JiraUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("StoryId");

                b.ToTable("Stories");
            });

        modelBuilder.Entity("Backlog.Core.TaskItem", b =>
            {
                b.Property<Guid>("TaskItemId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.HasKey("TaskItemId");

                b.ToTable("TaskItems");
            });

        modelBuilder.Entity("Backlog.Core.Technology", b =>
            {
                b.Property<Guid>("TechnologyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("TechnologyId");

                b.ToTable("Technologies");
            });

        modelBuilder.Entity("Backlog.Core.Story", b =>
            {
                b.OwnsMany("Backlog.Core.DependencyRelationship", "DependsOn", b1 =>
                    {
                        b1.Property<Guid>("StoryId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("int")
                            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                        b1.Property<string>("DependsOn")
                            .HasColumnType("nvarchar(max)");

                        b1.HasKey("StoryId", "Id");

                        b1.ToTable("DependencyRelationships");

                        b1.WithOwner()
                            .HasForeignKey("StoryId");
                    });

                b.OwnsMany("Backlog.Core.SkillRequirement", "SkillRequirements", b1 =>
                    {
                        b1.Property<Guid>("StoryId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("int")
                            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                        b1.Property<string>("CompetencyLevel")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Technology")
                            .HasColumnType("nvarchar(max)");

                        b1.HasKey("StoryId", "Id");

                        b1.ToTable("SkillRequirement");

                        b1.WithOwner()
                            .HasForeignKey("StoryId");
                    });

                b.Navigation("DependsOn");

                b.Navigation("SkillRequirements");
            });
#pragma warning restore 612, 618
    }
}